# Ensure that the VW and ASP meta.yaml files are in sync with each other and with 
# ISIS. 
# Specify the correct tag in git_tag, for example, 2.7.0, or a commit hash.

{% set version = "isis4.4.0" %} # synched up to isis dependencies for this version

package:
    name: stereo-pipeline
    version: {{ version }}

source:
  git_url: git@github.com:NeoGeographyToolkit/StereoPipeline.git
  git_tag: 7135505 # ensure the correct tag here

build:
    number: 0

requirements:
    build:
# Use the local compiler for OSX. See build.sh for details.
        - {{ compiler('c') }}    # [linux]
        - {{ compiler('cxx') }}  # [linux]
        - cmake                     3.16.0
        - llvm-openmp            # [osx]
#       - libgomp                # [linux]

    host:
        - gdal                      isis4.4.0
        - ilmbase
        - openexr
        - eigen                     3.3.7
        - pbzip2
        - gflags
        - glog
        - suitesparse               5.7.2
        - ceres-solver              1.14.0
        - parallel
        - flann                     1.9.1
        - opencv                    3.2.0
        - openmp                    # [linux]
        - boost                     1.68
        - liblapack                 3.8.0
        - blas                      1.1
        - geotiff                   1.4.2
        - proj4                     4.9.3
        - geos                      3.7.3
        - hdf5                      1.8.18
        - imagemagick               isis4.4.0
        - laszip                    2.1.0
        - liblas                    isis4.4.0
        - libnabo                   isis4.4.0
        - libpointmatcher           isis4.4.0
        - geoid                     1.0
        - htdp                      1.0
        - fgr                       isis4.4.0
        - theia                     isis4.4.0
        - isis                      4.4.0 # to catch dependency problems
        - usgscsm                   1.5.1
        - csm                       3.0.3.3
        - visionworkbench           isis4.4.0
    run:
        - gdal                      isis4.4.0
        - ilmbase
        - openexr
        - eigen                     3.3.7
        - pbzip2
        - gflags
        - glog
        - suitesparse               5.7.2
        - ceres-solver              1.14.0
        - parallel
        - flann                     1.9.1
        - opencv                    3.2.0
        - openmp                    # [linux]
        - boost                     1.68
        - liblapack                 3.8.0
        - blas                      1.1
        - geotiff                   1.4.2
        - proj4                     4.9.3
        - geos                      3.7.3
        - hdf5                      1.8.18
        - imagemagick               isis4.4.0
        - laszip                    2.1.0
        - liblas                    isis4.4.0
        - libnabo                   isis4.4.0
        - libpointmatcher           isis4.4.0
        - geoid                     1.0
        - htdp                      1.0
        - fgr                       isis4.4.0
        - theia                     isis4.4.0
        - isis                      4.4.0 # to catch dependency problems
        - usgscsm                   1.5.1
        - csm                       3.0.3.3
        - visionworkbench           isis4.4.0

test:
    files:
        imports:
        commands:
        comment: "Add here something like stereo_pprc --version"

about:
    home: https://github.com/NeoGeographyToolkit/StereoPipeline
    license: APACHE
    summary: A suite of automated geodesy & stereogrammetry tools
    summary: 

extra:
  recipe-maintainers:
    - oleg.alexandrov@gmail.com
