# Ensure that the VW and ASP meta.yaml files are in sync with each other and with 
# ISIS. 
{% set version = "3.6.0" %}

package:
    name: stereo-pipeline
    version: {{ version }}

source:
  # No git tag. Just built the latest. 
  git_url: git@github.com:NeoGeographyToolkit/StereoPipeline.git

build:
    number: 0

requirements:
    build:
        - cmake >=3.27,<3.28
        - make
        - c-compiler 1.7.0
        - cxx-compiler 1.7.0
        - fortran-compiler 1.7.0
        - git
        - wget

    host:
        - libunwind # [linux]
        - suitesparse
        # ceres needs a variant with suitesparse support
        - ceres-solver 2.2.0 h30ec75d_2  # [linux]
        - ceres-solver 2.2.0 h5cbf65c_1  # [osx and x86_64]
        - ceres-solver 2.2.0 h1a5cec8_1  # [osx and arm64]
        - chrpath # [linux]
        - fftw
        - gflags
        - glog
        # - libpdal-core # built from source for now
        - llvm-openmp
        - mesalib
        - parallel
        - pbzip2
        - rapidjson
        - rocksdb
        - vlfeat
        - usgscsm
        - isis 9.0.0

test:
    files:
        imports:
        commands:
        comment: "Add here something like stereo_pprc --version"

about:
    home: https://github.com/NeoGeographyToolkit/StereoPipeline
    license: APACHE II
    summary: A suite of automated stereogrammetry tools

extra:
  recipe-maintainers:
    - oleg.alexandrov@gmail.com
