# Ensure that the VW and ASP meta.yaml files are in sync with each other and with 
# ISIS. 
{% set version = "3.5.0" %}

package:
    name: stereo-pipeline
    version: {{ version }} # will compile this version

source:
  git_url: git@github.com:NeoGeographyToolkit/StereoPipeline.git
# No git tag. Just built the latest. More convenient this way.  
#  git_tag: {{ version }} # this tag must exist

build:
    number: 2

requirements:
    build:
        - cmake                     3.27.9
        # Compiler versions for ISIS compatibility
        - c-compiler                1.9.0
        - cxx-compiler              1.9.0

    host:
        - chrpath                   # [linux]
        - libglvnd                  # [linux]
        - llvm-openmp               16.0.6
        - parallel
        - pbzip2
        - geoid                     1.0_isis7
        - isis                      8.3.0
        - krb5                      1.21.2
        - fgr                       asp3.5.0
        - pdal                      2.6.0_asp3.5.0
        - libelas                   asp3.5.0
        - libpointmatcher           asp3.5.0
        - s2p-subset                asp3.5.0
        - usgscsm                   2.0.2
        - visionworkbench           asp3.5.0
        - multiview                 asp_3.5.0
        - eigen                     3.4.0
        - ceres-solver              2.2.0

    run:
        - chrpath                   # [linux]
        - libglvnd                  # [linux]
        - llvm-openmp               16.0.6
        - parallel
        - pbzip2
        - geoid                     1.0_isis7
        - isis                      8.3.0
        - krb5                      1.21.2
        - fgr                       asp3.5.0
        - pdal                      2.6.0_asp3.5.0
        - libelas                   asp3.5.0
        - libpointmatcher           asp3.5.0
        - s2p-subset                asp3.5.0
        - usgscsm                   2.0.2
        - visionworkbench           asp3.5.0
        - multiview                 asp_3.5.0
        - eigen                     3.4.0
        - ceres-solver              2.2.0

test:
    files:
        imports:
        commands:
        comment: "Add here something like stereo_pprc --version"

about:
    home: https://github.com/NeoGeographyToolkit/StereoPipeline
    license: APACHE II
    summary: A suite of automated stereogrammetry tools

extra:
  recipe-maintainers:
    - oleg.alexandrov@gmail.com
